alter table access_scope modify column user_detail_id int(11) not null;
alter table access_scope add column county_id int(11);
alter table access_scope add column sub_county_id int(11);
alter table access_scope modify column add_date datetime not null;
alter table access_scope modify column last_edit_date datetime;
alter table county modify column add_date datetime;
alter table county modify column last_edit_date datetime;
alter table data_element modify column data_element_name varchar(255);
alter table data_element modify column data_element_context varchar(255);
alter table data_element modify column description varchar(255);
alter table data_element modify column add_date datetime;
alter table data_element modify column last_edit_date datetime;
alter table data_element_sms_position modify column add_date datetime not null;
alter table data_element_sms_position modify column last_edit_date datetime;
alter table district modify column add_date datetime;
alter table district modify column last_edit_date datetime;
alter table health_facility modify column add_date datetime;
alter table health_facility modify column last_edit_date datetime;
alter table interface_data_sms modify column add_date datetime not null;
alter table interface_data_sms modify column last_edit_date datetime;
alter table organisation modify column add_date datetime not null;
alter table organisation modify column last_edit_date datetime;
alter table parish modify column add_date datetime;
alter table parish modify column last_edit_date datetime;
alter table phone_contact modify column add_date datetime not null;
alter table phone_contact modify column last_edit_date datetime;
alter table region modify column add_date datetime;
alter table region modify column last_edit_date datetime;
alter table report_form modify column add_date datetime;
alter table report_form modify column last_edit_date datetime;
alter table report_form_short_code modify column add_date datetime not null;
alter table report_form_short_code modify column last_edit_date datetime;
drop table report_form_update;
create table report_form_update (report_form_update_id int(11) not null auto_increment, report_form_id int(11) not null, last_edit_date datetime not null, primary key (report_form_update_id)) ENGINE=InnoDB;
alter table sub_county modify column add_date datetime;
alter table sub_county modify column last_edit_date datetime;
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';
alter table access_scope add constraint FKaccess_sco501789 foreign key (user_detail_id) references user_detail (user_detail_id);
alter table access_scope add constraint FKaccess_sco464218 foreign key (district_id) references district (district_id);
alter table access_scope add constraint FKaccess_sco613427 foreign key (health_facility_id) references health_facility (health_facility_id);
alter table access_scope add constraint FKaccess_sco579026 foreign key (parish_id) references parish (parish_id);
alter table access_scope add constraint FKaccess_sco450360 foreign key (sub_county_id) references sub_county (sub_county_id);
alter table access_scope add constraint FKaccess_sco114602 foreign key (county_id) references county (county_id);
alter table access_scope add constraint FKaccess_sco658777 foreign key (region_id) references region (region_id);
