alter table access_scope modify column add_date datetime not null;
alter table access_scope modify column last_edit_date datetime;
alter table county modify column add_date datetime;
alter table county modify column last_edit_date datetime;
alter table data_element modify column data_element_name varchar(255);
alter table data_element modify column data_element_context varchar(255);
alter table data_element modify column description varchar(255);
alter table data_element modify column add_date datetime;
alter table data_element modify column last_edit_date datetime;
alter table data_element_sms_position modify column add_date datetime not null;
alter table data_element_sms_position modify column last_edit_date datetime;
alter table deadline_extension modify column extended_to_date datetime not null;
alter table deadline_extension add column is_deleted int(1) not null;
alter table deadline_extension add column is_active int(1) not null;
alter table deadline_extension add column add_date datetime;
alter table deadline_extension add column add_by int(10);
alter table deadline_extension add column last_edit_date datetime;
alter table deadline_extension add column last_edit_by int(10);
alter table district modify column add_date datetime;
alter table district modify column last_edit_date datetime;
alter table health_facility modify column add_date datetime;
alter table health_facility modify column last_edit_date datetime;
alter table interface_data_sms modify column add_date datetime not null;
alter table interface_data_sms modify column last_edit_date datetime;
alter table organisation modify column add_date datetime not null;
alter table organisation modify column last_edit_date datetime;
alter table parish modify column add_date datetime;
alter table parish modify column last_edit_date datetime;
alter table phone_contact modify column add_date datetime not null;
alter table phone_contact modify column last_edit_date datetime;
alter table region modify column add_date datetime;
alter table region modify column last_edit_date datetime;
alter table report_form modify column add_date datetime;
alter table report_form modify column last_edit_date datetime;
alter table report_form_deadline modify column time_from time;
alter table report_form_deadline modify column time_to time;
alter table report_form_deadline add column is_deleted int(1) not null;
alter table report_form_deadline add column is_active int(1) not null;
alter table report_form_deadline add column add_date datetime;
alter table report_form_deadline add column add_by int(10);
alter table report_form_deadline add column last_edit_date datetime;
alter table report_form_deadline add column last_edit_by int(10);
alter table report_form_entity add column is_deleted int(1) not null;
alter table report_form_entity add column is_active int(1) not null;
alter table report_form_entity add column add_date datetime;
alter table report_form_entity add column add_by int(10);
alter table report_form_entity add column last_edit_date datetime;
alter table report_form_entity add column last_edit_by int(10);
alter table report_form_short_code modify column add_date datetime not null;
alter table report_form_short_code modify column last_edit_date datetime;
alter table report_form_update modify column last_edit_date datetime not null;
alter table sent_sms_log modify column sent_date datetime not null;
alter table sent_sms_log add column is_deleted int(1) not null;
alter table sent_sms_log add column is_active int(1) not null;
alter table sent_sms_log add column add_date datetime;
alter table sent_sms_log add column add_by int(10);
alter table sent_sms_log add column last_edit_date datetime;
alter table sent_sms_log add column last_edit_by int(10);
alter table sms_recipient add column is_deleted int(1) not null;
alter table sms_recipient add column is_active int(1) not null;
alter table sms_recipient add column add_date datetime;
alter table sms_recipient add column add_by int(10);
alter table sms_recipient add column last_edit_date datetime;
alter table sms_recipient add column last_edit_by int(10);
alter table sms_schedule modify column send_date datetime;
alter table sms_schedule add column is_deleted int(1) not null;
alter table sms_schedule add column is_active int(1) not null;
alter table sms_schedule add column add_date datetime;
alter table sms_schedule add column add_by int(10);
alter table sms_schedule add column last_edit_date datetime;
alter table sms_schedule add column last_edit_by int(10);
alter table sub_county modify column add_date datetime;
alter table sub_county modify column last_edit_date datetime;
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';
