create table access_scope (access_scope_id int(11) not null auto_increment, user_detail_id int(11), region_id int(11), district_id int(11), parish_id int(11), health_facility_id int(11), primary key (access_scope_id)) ENGINE=InnoDB;
alter table data_element modify column data_element_name varchar(255);
alter table data_element modify column data_element_context varchar(255);
alter table data_element modify column description varchar(255);
alter table data_element modify column add_date datetime;
alter table data_element modify column last_edit_date datetime;
create table data_element_sms_position (data_element_sms_position_id int(11) not null auto_increment, data_element_id int(11) not null, value_position int(2) not null, code_position int(2) not null, report_form_short_code_id int(11), primary key (data_element_sms_position_id)) ENGINE=InnoDB;
create table interface_data_sms (interface_data_sms_id int(11) not null auto_increment, add_date datetime not null, phone varchar(100) not null, sms varchar(255), scode varchar(11), status_code varchar(100), status_desc varchar(250), report_form_code varchar(100), primary key (interface_data_sms_id)) ENGINE=InnoDB;
create table organisation (organisation_id int(11) not null auto_increment, organisation_name varchar(100) not null, is_active int(1) not null, primary key (organisation_id)) ENGINE=InnoDB;
create table phone_contact (phone_contact_id int(11) not null auto_increment, entity_type varchar(20) not null, entity_id int(11) not null, entity_phone varchar(100) not null, primary key (phone_contact_id)) ENGINE=InnoDB;
alter table report_form modify column add_date datetime;
alter table report_form modify column last_edit_date datetime;
create table report_form_short_code (report_form_short_code_id int(11) not null auto_increment, start_code varchar(50) not null, seperators int(2), short_code varchar(255) not null, primary key (report_form_short_code_id)) ENGINE=InnoDB;
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail add column organisation_id int(11);
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';
alter table user_detail add index FKuser_detai192219 (organisation_id), add constraint FKuser_detai192219 foreign key (organisation_id) references organisation (organisation_id);
alter table data_element_sms_position add index FKdata_eleme360408 (data_element_id), add constraint FKdata_eleme360408 foreign key (data_element_id) references data_element (data_element_id);
alter table data_element_sms_position add index FKdata_eleme644022 (report_form_short_code_id), add constraint FKdata_eleme644022 foreign key (report_form_short_code_id) references report_form_short_code (report_form_short_code_id);
alter table access_scope add column is_deleted int(1) not null;
alter table access_scope add column is_active int(1) not null;
alter table access_scope add column add_date datetime;
alter table access_scope add column add_by int(10);
alter table access_scope add column last_edit_date datetime;
alter table access_scope add column last_edit_by int(10);
alter table data_element modify column data_element_name varchar(255);
alter table data_element modify column data_element_context varchar(255);
alter table data_element modify column description varchar(255);
alter table data_element modify column add_date datetime;
alter table data_element modify column last_edit_date datetime;
alter table data_element_sms_position add column is_deleted int(1) not null;
alter table data_element_sms_position add column is_active int(1) not null;
alter table data_element_sms_position add column add_date datetime;
alter table data_element_sms_position add column add_by int(10);
alter table data_element_sms_position add column last_edit_date datetime;
alter table data_element_sms_position add column last_edit_by int(10);
alter table interface_data_sms modify column add_date datetime not null;
alter table interface_data_sms add column is_deleted int(1) not null;
alter table interface_data_sms add column is_active int(1) not null;
alter table interface_data_sms add column add_by int(10);
alter table interface_data_sms add column last_edit_date datetime;
alter table interface_data_sms add column last_edit_by int(10);
alter table organisation add column is_deleted int(1) not null;
alter table organisation add column add_date datetime;
alter table organisation add column add_by int(10);
alter table organisation add column last_edit_date datetime;
alter table organisation add column last_edit_by int(10);
alter table phone_contact add column is_deleted int(1) not null;
alter table phone_contact add column is_active int(1) not null;
alter table phone_contact add column add_date datetime;
alter table phone_contact add column add_by int(10);
alter table phone_contact add column last_edit_date datetime;
alter table phone_contact add column last_edit_by int(10);
alter table report_form modify column add_date datetime;
alter table report_form modify column last_edit_date datetime;
alter table report_form_short_code add column is_deleted int(1) not null;
alter table report_form_short_code add column is_active int(1) not null;
alter table report_form_short_code add column add_date datetime;
alter table report_form_short_code add column add_by int(10);
alter table report_form_short_code add column last_edit_date datetime;
alter table report_form_short_code add column last_edit_by int(10);
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';





alter table access_scope modify column add_date datetime;
alter table access_scope modify column last_edit_date datetime;
alter table data_element modify column data_element_name varchar(255);
alter table data_element modify column data_element_context varchar(255);
alter table data_element modify column description varchar(255);
alter table data_element modify column add_date datetime;
alter table data_element modify column last_edit_date datetime;
alter table data_element_sms_position modify column add_date datetime;
alter table data_element_sms_position modify column last_edit_date datetime;
alter table interface_data_sms modify column add_date datetime not null;
alter table interface_data_sms modify column last_edit_date datetime;
alter table organisation modify column add_date datetime;
alter table organisation modify column last_edit_date datetime;
alter table phone_contact modify column add_date datetime;
alter table phone_contact modify column last_edit_date datetime;
alter table report_form modify column add_date datetime;
alter table report_form modify column last_edit_date datetime;
alter table report_form_short_code modify column add_date datetime;
alter table report_form_short_code modify column last_edit_date datetime;
alter table user_detail modify column add_date datetime;
alter table user_detail modify column last_edit_date datetime;
alter table user_detail comment = 'Stores user details such as username, password, type, status, etc';
